### PR TITLE
Added Controller for Adding Ride

### PR DESCRIPTION
**Pull request by KarthikBalajiB**
**Spring Boot REST Controller:** 
Manages ride data for the ShareTaxi app.

**Endpoints Provided:**

- Retrieve all rides.
- Filter rides by driver ID.
- Query rides by starting point and destination.
- Find rides scheduled for a specific date.
- Get rides with available seats.
- Retrieve rides within a specific time range.
- Fetch rides by ride status.
- Add a Ride

Please review and let me know if there is any suggestions/changes.

### CODE REVIEW

**Review by christopher-2000 — COMMENTED** [review]
Add the Endpoint to add a ride as well.

**Comment by KarthikBalajiB** [comment]
> Add the Endpoint to add a ride as well.

Thanks for the suggestion Chris. Added the functionality to add the ride as well.

**Review by christopher-2000 — APPROVED** [review]
Okay looks good

**Comment by neharajeeva** [comment]
I feel it is good to go!

**Pull request merged**
